version: "3.9"
services:
  api: &api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: nrc-transaction-logic
    command: python manage.py runserver 0.0.0.0:10009
    volumes:
      - ./app:/app
    ports:
      - "10009:10009"
    env_file:
      - ./.env
    restart: always

